name: Retrieve XML

on:
  push:
    branches:
      - master

jobs:

  get-xml-info:
    runs-on: ubuntu-latest
    name: Gets feed XML
    steps:
      -name: get xml
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: 'https://bobbiejwilson.github.io/feed.xml'
          xpath: '//entry'