name: Retrieve XML

on:
  push:
    branches:
    - master

jobs:
  build:
    needs: pages-build-deployment
    runs-on: ubuntu-latest
    steps:
    - name: Get XML
        
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: 'feed.xml'
          xpath: '/feed/entry[1]'